sudo: required
language: java
jdk: oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

script:
  - gradle clean
  - gradle wrapper
  - ./gradlew build buildDocker --info


after_success:
- bash <(curl -s https://codecov.io/bash)
- sh ./deploy/docker_pusher.sh

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - echo 'download google cloud sdk'
  - echo '=============================update kubectl============================='
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - echo '=============================finish update=============================='

deploy:
  - provider: script
    script: sh ./deploy/deploy.sh
    skip_cleanup: true
    on:
#      all_branches: true
      branch: dev
