apiVersion: v1
kind: Service
metadata:
  name: product-type
  labels:
    name: product-type
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    name: product-type
