kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: dev
    name: product-type
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: product-type
      spec:
        containers:
        - name: product-type
          image: reactivesw/product-type:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_datasource_url
            value: jdbc:postgresql://reactivesw-data/product_type
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: reactivesw-secret
                key: postgres.username
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: reactivesw-secret
                key: postgres.password
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: reactivesw-secret
                key: jwt.secret
- kind: Service
  apiVersion: v1
  metadata:
    name: product-type
    namespace: dev
    labels:
      name: product-type
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30110
    selector:
      name: product-type